### ISSUE TITLE
Ink or Black Lotus

### ISSUE THREAD

**Issue by Uimori** [Ellpeck/AAtMtM#13]
Need a way to get Ink or Black Lotus since squids don't spawn in the forest biome. Needed to empower Enori and Void.

**Comment by Ellpeck** [comment]
What are you trying to make?

**Comment by Uimori** [comment]
Empowered enori to make a bio reactor. But I also wanted to upgrade batteries.

**Comment by Ellpeck** [comment]
People on the official modpack server are saying that they got squids to spawn just fine, so I'm a bit confused as to why it doesn't work for you. I'll add a recipe, though.

**Comment by Uimori** [comment]
Apparently it's not necessary. Somebody reminded me that the Lens of Color can handle it. so this is a non issue anymore.
